version: '2'
services:
  db:
    restart: always
    build: 'data-loader'
    image: rspeer/conceptnet-data:5.5.5
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=conceptnet5
    volumes:
      - data:/data/conceptnet
      - psql:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

  api:
    build: '.'
    image: rspeer/conceptnet:5.5.5
    links:
      - db
    ports:
      - "80:80"
    environment:
      - CONCEPTNET_DB_HOSTNAME=db
      - CONCEPTNET_BUILD_DATA=/data/conceptnet
      - CONCEPTNET_DATA=/data/conceptnet
      - CONCEPTNET_RATE_LIMITING=0
    volumes:
      - data:/data/conceptnet
      - cache:/data/nginx
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "10"

volumes:
  psql:
  data:
  cache:
